name: E2E Tests

on:
  push:
    branches: [dev, main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend
        uses: actions/checkout@v2

      - name: Checkout backend (API)
        uses: actions/checkout@v2
        repository: '${{ secrets.BACKEND_REPOSITORY_URL }}'
        ref: 'main'
        with:
          start: npm start
          wait-on: http://localhost:5000

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: http://localhost:3000
